### ISSUE TITLE
Error in textConnection(dataTsv)

### ISSUE THREAD

**Issue by galanisl** [aGutierrezSacristan/psygenet2r#1]
Hi @aGutierrezSacristan ,

I'm trying to reproduce the results from your vignette (https://www.bioconductor.org/packages/release/bioc/vignettes/psygenet2r/inst/doc/general_overview.html) but I get the following error:

`Error in textConnection(dataTsv) : invalid 'text' argument`

This is the code that I'm trying to run:

```
library(psygenet2r)
genesOfInterest <- c( "COMT", "CLOCK", "DRD3", "GNB3", "HTR1A",
    "MAOA", "HTR2A","HTR2C", "HTR6", "SLC6A4", "ACE",  "BDNF", 
    "DRD4", "HTR1B", "HTR2B", "HTR2C", "MTHFR", "SLC6A3", "TPH1", 
    "SLC6A2", "GABRA3"
)
m1 <- psygenetGene(
  gene     = genesOfInterest, 
  database = "ALL",
  verbose  = TRUE
)
```

**Comment by aGutierrezSacristan** [comment]
Hi @galanisl, could you give me some other information to try to reproduce your error? I am running the same code and I am not getting any error:

![Screen Shot 2021-02-24 at 12 44 06 PM](https://user-images.githubusercontent.com/19646530/109042322-12f6b300-769e-11eb-8a39-9150bd2f087c.png)
 
I am running it in: 
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

**Comment by galanisl** [comment]
@aGutierrezSacristan  Thanks for the quick reply. Here's my session info:

sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.4 (Nitrogen)

Matrix products: default
BLAS/LAPACK: /apps/prod/easybuild/sl7.x86_64/software/OpenBLAS/0.3.9-GCC-9.3.0/lib/libopenblasp-r0.3.9.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] psygenet2r_1.20.0

**Comment by aGutierrezSacristan** [comment]
The only difference I can find is the psygenet2r version, I think you have installed an old version of the package, could you try to install the las one? 
psygenet2r_1.23.3

**Comment by galanisl** [comment]
Thanks a lot @aGutierrezSacristan . I installed the package using the code below, which installed 1.23.3, and that solved the issue. Probably worth updating the README as the installation from bitbucket didn't work for me.

```
library(devtools)
install_github("aGutierrezSacristan/psygenet2r")
```

**Comment by aGutierrezSacristan** [comment]
Great, happy to hear that it works now! I have updated the Readme, sorry about that, I did not realized it was not updated. thank you @galanisl!
