### ISSUE TITLE
Error in textConnection(dataTsv) : invalid 'text' argument

### ISSUE THREAD

**Issue by yifnzhao** [aGutierrezSacristan/psygenet2r#2]
Hi @aGutierrezSacristan ,

Thanks for developing this package. I tried the following command:
```
> library(psygenet2r)
> qd <- psygenetDisease(disease = "schizophrenia", 
                       database = "ALL",
                       evidenceIndex = c('>', 0.5) 
```
which gives me an error: ```Error in textConnection(dataTsv) : invalid 'text' argument```

I noticed this was also brought up in Issue #1 and have followed the installation instruction in the README, but the error still persists.

The package version is:
```
> packageVersion("psygenet2r")
[1] ‘1.23.3’
```

Thanks in advance for your help.

Best,
Yifan

**Comment by aGutierrezSacristan** [comment]
Hi @yifnzhao , 

Thanks for reporting this. I am trying to reproduce the error, but it is running fine for me. 
I checked and package version looks fine. Maybe some dependencies?

See attached the screenshot of my try to reproduce your error:
![Screenshot 2021-04-17 at 18 39 04](https://user-images.githubusercontent.com/19646530/115128545-8638e900-9fac-11eb-8550-544a6caf7931.png)

**Comment by yifnzhao** [comment]
Thanks for checking. I reinstalled the package and updated all dependencies, and it is working now.

**Comment by aGutierrezSacristan** [comment]
Awesome!
