### ISSUE TITLE
List of genes

### ISSUE THREAD

**Issue by Elseedy28** [aGutierrezSacristan/psygenet2r#3]
Hello ,
i am new in psygent2r , i would like to ask if i need to analyse (DEG) around 1826 genes with this package what is the code that i will need to use a CSV file instead of writing all the genes manually

Sorry for that 
heba

**Comment by Elseedy28** [comment]
when i add the list i had this error
<img width="1728" alt="Capture d’écran 2023-03-15 à 13 16 51" src="https://user-images.githubusercontent.com/115556489/225306723-ca3bd23d-d371-40bb-b267-fb85628ee377.png">
what does it means?

**Comment by Elseedy28** [comment]
and  i tried to put some genes i had this error
Staring querying PsyGeNET for MSLN, IFNLR1, LAMA3, KCNH2, LAMC2, SPP1, DUSP5, POLR1C, FMN1, MMP8, DRD5, CD93, SLC36A4, TFPI2, ADAMTS17, LHX2, GATM, TTLL1, HPSE, ROR1, SCLY, NR4A2, L3MBTL3, EHD2, STAB2, UCMA, PGBD1, LILRAB, FBXO7, PLA2G4B, PPM1L, PABIR3, CCDC82, ADK, FAM210B, CPED1, DYNC1I1, TRIM10, LPL, GPR84, CACNA1H, ACADM, CASKIN1, FLYWCH2, IGFL4, TIMP2, MSRB3, SMIM1, RNF152, TNFAIP8L1, RAB27B, TNS1, AKR1B10, ABO in ALL database.
Warning message:
In psygenetGene(gene = genesOfInterest, database = "ALL", verbose = TRUE) :
  One or more of the given genes is not in PsyGeNET ( 'ALL' ):
MSLN, IFNLR1, LAMA3, LAMC2, SPP1, DUSP5, POLR1C, FMN1, CD93, SLC36A4, TFPI2, ADAMTS17, LHX2, GATM, TTLL1, SCLY, L3MBTL3, EHD2, STAB2, UCMA, PGBD1, LILRAB, FBXO7, PPM1L, PABIR3, CCDC82, FAM210B, CPED1, DYNC1I1, TRIM10, GPR84, CACNA1H, ACADM, CASKIN1, FLYWCH2, IGFL4, TIMP2, MSRB3, SMIM1, RNF152, TNFAIP8L1, RAB27B, TNS1, AKR1B10

**Comment by aGutierrezSacristan** [comment]
Hi Heba, thanks for using the psygenet2r package. 
For importing your list of genes from a csv file, you can use the R functions read.csv or read.delim. Then depending on how your file is formatted you will need to make sure you are transforming the data frame into a vector, that is the input for some of our functions. So for example, if you are importing a csv and when you do a head() of your imported table, you see that the column name of your genes is, V1, then you would do something like:

mygenes <- as.character( mydataframe$V1)

And then you can call for example, the psygenetGene() function giving as input your vector of genes:
psygenetGene( mygenes, "ALL" )

Regarding the warning message you are getting when running psygenetGene() it is not an error, is a warning, just saying that out of all your input genes, these ones are not in psygenet database. You can look for example for the MSLN gene in the psygenet broswer http://psygenet.org/web/PsyGeNET and you will see that the output is the same, the gene is not included in psygenet. Think that PysGenet was a manual curation effort, but that the last update was in 2016. I would recommend you to use other platforms if your overlap between your genes of interest and the genes in psygenet is low. A resource you can find useful is disgenet, https://www.disgenet.org/ that is more updated and intergates other sources of information.
